apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        image: kubernautslabs/jmeter_master:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while [ ! -f /tmp/isdone ]; do sleep 30; done;" ]
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
            subPath: "load_test"
          - name: azure
            mountPath: "/mnt/azure"
        ports:
        - containerPort: 60000
      restartPolicy: OnFailure
      volumes:
      - name: loadtest 
        configMap:
         name: jmeter-load-test
      - name: azure
        azureFile:  # https://docs.microsoft.com/en-us/azure/aks/azure-files-volume
          secretName: jmeterlogsecret
          shareName: jmeterlogs
          readOnly: false