apiVersion: batch/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Job
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  # replicas: 1
  #selector:
  #  matchLabels:
  #    jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        env:
        - name: 'JVM_ARGS'
          value: '-Xms756M -Xmx756M'
        image: kubernautslabs/jmeter_master:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:  
            memory: "1024Mi"
            cpu: "2000m"
          limits:
            memory: "1500Mi"
            cpu: "4000m"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while [ ! -f /tmp/isdone ]; do sleep 30; done;" ]
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
            subPath: "load_test"
          - name: azure
            mountPath: "/mnt/azure"
        ports:
        - containerPort: 60000
      restartPolicy: OnFailure
      volumes:
      - name: loadtest 
        configMap:
         name: jmeter-load-test
      - name: azure
        azureFile:  # https://docs.microsoft.com/en-us/azure/aks/azure-files-volume
          secretName: jmeterlogsecret
          shareName: jmeterlogs
          readOnly: false