kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: overseer
  namespace: orchestrator
subjects:
- kind: ServiceAccount
  name: default
  namespace: orchestrator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io